## Ch03 - Churn Prediction Project

### 3.1 Data Preparation

Download the data, read it with pandas.<br>
Look at the data<br>
Make column name and values look uniform <br>
Check if all the column read correctly <br>
Check if the churn variable needs any preparation <br>

In [1]:
import pandas as pd
import numpy as np

import seaborn as sns
from matplotlib import pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv('data.csv')

In [3]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [4]:
# Since we cannot see all the columns in one go, we transpose the dataset to see all the colunms

df.head().T

,0,1,2,3,4
customerID,7590-VHVEG,5575-GNVDE,3668-QPYBK,7795-CFOCW,9237-HQITU
gender,Female,Male,Male,Male,Female
SeniorCitizen,0,0,0,0,0
Partner,Yes,No,No,No,No
Dependents,No,No,No,No,No
tenure,1,34,2,45,2
PhoneService,No,Yes,Yes,No,Yes
MultipleLines,No phone service,No,No,No phone service,No
InternetService,DSL,DSL,DSL,DSL,Fiber optic
OnlineSecurity,No,Yes,Yes,Yes,No
OnlineBackup,Yes,No,Yes,No,No
DeviceProtection,No,Yes,No,Yes,No
TechSupport,No,No,No,Yes,No
StreamingTV,No,No,No,No,No
StreamingMovies,No,No,No,No,No
Contract,Month-to-month,One year,Month-to-month,One year,Month-to-month
PaperlessBilling,Yes,No,Yes,No,Yes
PaymentMethod,Electronic check,Mailed check,Mailed check,Bank transfer (automatic),Electronic check
MonthlyCharges,29.85,56.95,53.85,42.3,70.7
TotalCharges,29.85,1889.5,108.15,1840.75,151.65
Churn,No,No,Yes,No,Yes

In [5]:
# Now lets clean the dataset
# begins with the columns

df.columns = df.columns.str.lower().str.replace(' ', '_')

categorical_columns = list(df.dtypes[df.dtypes == 'object'].index)

for c in categorical_columns:
    df[c] = df[c].str.lower().str.replace(' ', '_')

In [6]:
df.head().T

,0,1,2,3,4
customerid,7590-vhveg,5575-gnvde,3668-qpybk,7795-cfocw,9237-hqitu
gender,female,male,male,male,female
seniorcitizen,0,0,0,0,0
partner,yes,no,no,no,no
dependents,no,no,no,no,no
tenure,1,34,2,45,2
phoneservice,no,yes,yes,no,yes
multiplelines,no_phone_service,no,no,no_phone_service,no
internetservice,dsl,dsl,dsl,dsl,fiber_optic
onlinesecurity,no,yes,yes,yes,no
onlinebackup,yes,no,yes,no,no
deviceprotection,no,yes,no,yes,no
techsupport,no,no,no,yes,no
streamingtv,no,no,no,no,no
streamingmovies,no,no,no,no,no
contract,month-to-month,one_year,month-to-month,one_year,month-to-month
paperlessbilling,yes,no,yes,no,yes
paymentmethod,electronic_check,mailed_check,mailed_check,bank_transfer_(automatic),electronic_check
monthlycharges,29.85,56.95,53.85,42.3,70.7
totalcharges,29.85,1889.5,108.15,1840.75,151.65
churn,no,no,yes,no,yes

In [7]:
df.dtypes

customerid           object
gender               object
seniorcitizen         int64
partner              object
dependents           object
tenure                int64
phoneservice         object
multiplelines        object
internetservice      object
onlinesecurity       object
onlinebackup         object
deviceprotection     object
techsupport          object
streamingtv          object
streamingmovies      object
contract             object
paperlessbilling     object
paymentmethod        object
monthlycharges      float64
totalcharges         object
churn                object
dtype: object

In [8]:
tc = pd.to_numeric(df.totalcharges, errors = 'coerce')

df.totalcharges = pd.to_numeric(df.totalcharges, errors = 'coerce')

df.totalcharges = df.totalcharges.fillna(0)

In [9]:
df.churn.head()

0     no
1     no
2    yes
3     no
4    yes
Name: churn, dtype: object

In [10]:
df.churn = (df.churn == 'yes').astype(int)

### 3.2 Setting up the Validation Framework

Prepare the train/validation/test split with Scikit-Learn

In [11]:
# Lets split the data from sklearn.model.model_selection
from sklearn.model_selection import train_test_split

df_full_train, df_test = train_test_split(df, test_size = 0.2, random_state = 1)

In [12]:
df_train , df_val = train_test_split(df_full_train, test_size = 0.25, random_state = 1)

In [13]:
df_train = df_train.reset_index(drop = True)
df_val = df_val.reset_index(drop = True)
df_test = df_test.reset_index(drop = True)

In [14]:
y_train = df_train.churn.values
y_val = df_val.churn.values
y_test = df_test.churn.values

In [15]:
del df_train['churn']
del df_val['churn']
del df_test['churn']

### 3.3 EDA - Exploratory Data Analysis

Check for missing values<br>
Look at the target variable<br>
Look at numerical and categorical variables<br>

In [16]:
df_full_train = df_full_train.reset_index(drop = True)

In [17]:
df_full_train.isnull().sum()

# there is no NaN values

customerid          0
gender              0
seniorcitizen       0
partner             0
dependents          0
tenure              0
phoneservice        0
multiplelines       0
internetservice     0
onlinesecurity      0
onlinebackup        0
deviceprotection    0
techsupport         0
streamingtv         0
streamingmovies     0
contract            0
paperlessbilling    0
paymentmethod       0
monthlycharges      0
totalcharges        0
churn               0
dtype: int64

In [18]:
# now lets look at the churn values and its counts, normalize helps to show the % of the values
df_full_train.churn.value_counts(normalize = True)

churn
0    0.730032
1    0.269968
Name: proportion, dtype: float64

In [19]:
# in the above answer o and 1 and its % , the 0.269968 is called churn rate, at which the people churn
# If we take the mean of the churn, then that answer will be equal to the churn rate. ie, bcoz the values in column churn is binary

global_churn_rate =  df_full_train.churn.mean()
round(global_churn_rate, 2)

np.float64(0.27)

In [20]:
# Noe lets seperate all the numerical and categorical values

df.columns

numerical = ['tenure','monthlycharges','totalcharges' ]

categorical = ['gender', 'seniorcitizen', 'partner', 'dependents',
     'phoneservice', 'multiplelines', 'internetservice',
       'onlinesecurity', 'onlinebackup', 'deviceprotection', 'techsupport',
       'streamingtv', 'streamingmovies', 'contract', 'paperlessbilling',
       'paymentmethod']

In [21]:
# Just to see all the unique categorical values
df_full_train[categorical].nunique()

gender              2
seniorcitizen       2
partner             2
dependents          2
phoneservice        2
multiplelines       3
internetservice     3
onlinesecurity      3
onlinebackup        3
deviceprotection    3
techsupport         3
streamingtv         3
streamingmovies     3
contract            3
paperlessbilling    2
paymentmethod       4
dtype: int64

### 3.4 Feature importance : Churn rate and Risk ratio

Feature important analysis (part of EDA) - Identifying which feature affects our target variable<br>

Churn rate<br>
Risk ratio<br>
Mutual Information - Later<br>

In [22]:
# Now lets just look into the dataset and understand how much some features have influenced 

churn_female = df_full_train[df_full_train['gender'] == 'female'].churn.mean()
churn_female

np.float64(0.27682403433476394)

In [23]:
churn_male = df_full_train[df_full_train['gender'] == 'male'].churn.mean()
churn_male

# Looks like the gender doesn't have a great impact in the global churn rate

np.float64(0.2632135306553911)

In [24]:
global_churn_rate

np.float64(0.26996805111821087)

In [25]:
# now lets look another feature, partner

churn_partner = df_full_train[df_full_train['partner'] == 'yes'].churn.mean()
churn_partner

np.float64(0.20503330866025166)

In [26]:
churn_no_partner = df_full_train[df_full_train['partner'] == 'no'].churn.mean()
churn_no_partner

np.float64(0.3298090040927694)

In [27]:
# See, this one has an average difference of 6%. 
# ie, customers with no partners have more churn than customers with partner when we compare with global churn rate

In [28]:
# Now we need to find a way to do this calculation to all the features without manually doing.
# first lets see an SQL quary to do this and the lets do it in pandas

SELECT

    gender,

    AVG(churn),

    AVG(churn) global_churn AS diff,

    AVG(churn) / global_churn AS risk

FROM

    data

GROUP BY

    gender;

In [29]:
# In pandas we cannot do this whole things in one function.
# we need to do things step by step

df_group = df_full_train.groupby('gender').churn.agg(['mean', 'count'])
df_group['diff'] =  df_group['mean'] -  global_churn_rate 
df_group['risk'] = df_group['mean'] / global_churn_rate

# This is how, we find the relevent details for one feature.
# So to do this to all the required feature, we can use a loop

In [30]:
# First lets import a library to display the values in the loop

from IPython.display import display

In [31]:
for c in categorical : 
    print(c)
    df_group = df_full_train.groupby(c).churn.agg(['mean', 'count'])
    df_group['diff'] =  df_group['mean'] -  global_churn_rate 
    df_group['risk'] = df_group['mean'] / global_churn_rate
    display(df_group)
    print()
    print()

gender

            mean  count      diff      risk
gender
female  0.276824   2796  0.006856  1.025396
male    0.263214   2838 -0.006755  0.974980

seniorcitizen

                   mean  count      diff      risk
seniorcitizen
0              0.242270   4722 -0.027698  0.897403
1              0.413377    912  0.143409  1.531208

partner

             mean  count      diff      risk
partner
no       0.329809   2932  0.059841  1.221659
yes      0.205033   2702 -0.064935  0.759472

dependents

                mean  count      diff      risk
dependents
no          0.313760   3968  0.043792  1.162212
yes         0.165666   1666 -0.104302  0.613651

phoneservice

                  mean  count      diff      risk
phoneservice
no            0.241316    547 -0.028652  0.893870
yes           0.273049   5087  0.003081  1.011412

multiplelines

                      mean  count      diff      risk
multiplelines
no                0.257407   2700 -0.012561  0.953474
no_phone_service  0.241316    547 -0.028652  0.893870
yes               0.290742   2387  0.020773  1.076948

internetservice

                     mean  count      diff      risk
internetservice
dsl              0.192347   1934 -0.077621  0.712482
fiber_optic      0.425171   2479  0.155203  1.574895
no               0.077805   1221 -0.192163  0.288201

onlinesecurity

                         mean  count      diff      risk
onlinesecurity
no                   0.420921   2801  0.150953  1.559152
no_internet_service  0.077805   1221 -0.192163  0.288201
yes                  0.153226   1612 -0.116742  0.567570

onlinebackup

                         mean  count      diff      risk
onlinebackup
no                   0.404323   2498  0.134355  1.497672
no_internet_service  0.077805   1221 -0.192163  0.288201
yes                  0.217232   1915 -0.052736  0.804660

deviceprotection

                         mean  count      diff      risk
deviceprotection
no                   0.395875   2473  0.125907  1.466379
no_internet_service  0.077805   1221 -0.192163  0.288201
yes                  0.230412   1940 -0.039556  0.853480

techsupport

                         mean  count      diff      risk
techsupport
no                   0.418914   2781  0.148946  1.551717
no_internet_service  0.077805   1221 -0.192163  0.288201
yes                  0.159926   1632 -0.110042  0.592390

streamingtv

                         mean  count      diff      risk
streamingtv
no                   0.342832   2246  0.072864  1.269897
no_internet_service  0.077805   1221 -0.192163  0.288201
yes                  0.302723   2167  0.032755  1.121328

streamingmovies

                         mean  count      diff      risk
streamingmovies
no                   0.338906   2213  0.068938  1.255358
no_internet_service  0.077805   1221 -0.192163  0.288201
yes                  0.307273   2200  0.037305  1.138182

contract

                    mean  count      diff      risk
contract
month-to-month  0.431701   3104  0.161733  1.599082
one_year        0.120573   1186 -0.149395  0.446621
two_year        0.028274   1344 -0.241694  0.104730

paperlessbilling

                      mean  count      diff      risk
paperlessbilling
no                0.172071   2313 -0.097897  0.637375
yes               0.338151   3321  0.068183  1.252560

paymentmethod

                               mean  count      diff      risk
paymentmethod
bank_transfer_(automatic)  0.168171   1219 -0.101797  0.622928
credit_card_(automatic)    0.164339   1217 -0.105630  0.608733
electronic_check           0.455890   1893  0.185922  1.688682
mailed_check               0.193870   1305 -0.076098  0.718121

### 3.5 Feature Importance : Mutual Information

Mutual information - concept from information theory, it tells us how much we can learn about one variable if we know the value of another

In [32]:
from sklearn.metrics import mutual_info_score

mutual_info_score(df_full_train.churn, df_full_train.contract)

# This function takes target and the feature that we need to learn as input
# the order inside the paranthesis doesn't matter
# Higher the score, it has greater impact in churn rate

0.0983203874041556

In [33]:
mutual_info_score(df_full_train.partner, df_full_train.churn)

0.009967689095399745

In [34]:
mutual_info_score(df_full_train.churn, df_full_train.gender)

0.0001174846211139946

In [35]:
# Now lets do this to all the features, for that we need to have a function

def mutual_info_churn_score(series):
        return mutual_info_score(series, df_full_train.churn)

In [36]:
mi = df_full_train[categorical].apply(mutual_info_churn_score)
mi.sort_values(ascending = False)

contract            0.098320
onlinesecurity      0.063085
techsupport         0.061032
internetservice     0.055868
onlinebackup        0.046923
deviceprotection    0.043453
paymentmethod       0.043210
streamingtv         0.031853
streamingmovies     0.031581
paperlessbilling    0.017589
dependents          0.012346
partner             0.009968
seniorcitizen       0.009410
multiplelines       0.000857
phoneservice        0.000229
gender              0.000117
dtype: float64

### 3.6 Feature Importance : Correlation

In [37]:
# In this session, we are going to look at the numerical values

In [38]:
df_full_train[numerical].corrwith(df_full_train.churn)

tenure           -0.351885
monthlycharges    0.196805
totalcharges     -0.196353
dtype: float64

In [39]:
df_full_train[df_full_train.tenure <= 2].churn.mean()

np.float64(0.5953420669577875)

In [40]:
df_full_train[(df_full_train.tenure > 2) & (df_full_train.tenure <= 12)].churn.mean()

np.float64(0.3994413407821229)

In [41]:
df_full_train[df_full_train.tenure > 12].churn.mean()

np.float64(0.17634908339788277)

In [42]:
# From the above observation, we can see that the churn rate decreases as the tenure increases. This is Negative Correlation

In [43]:
df_full_train[df_full_train.monthlycharges <= 20].churn.mean()

np.float64(0.08795411089866156)

In [44]:
df_full_train[(df_full_train.monthlycharges > 20) & (df_full_train.monthlycharges <= 50)].churn.mean()

np.float64(0.18340943683409436)

In [45]:
df_full_train[df_full_train.monthlycharges > 50].churn.mean()

np.float64(0.32499341585462205)

In [46]:
# Here, the churn rate increases as the monthly charge increases. This is Positive Correlation

### 3.7 One-hot Encoding

Use Scikit-Learn to encode categorical features

In [48]:
from sklearn.feature_extraction import DictVectorizer

In [54]:
df_train[['gender', 'contract']].iloc[:100]

    gender        contract
0   female        two_year
1     male  month-to-month
2   female  month-to-month
3   female  month-to-month
4   female        two_year
..     ...             ...
95    male        one_year
96  female  month-to-month
97    male  month-to-month
98    male        one_year
99    male  month-to-month

[100 rows x 2 columns]

In [55]:
dicts = df_train[['gender', 'contract']].iloc[:100].to_dict(orient = 'records')

In [60]:
dv = DictVectorizer(sparse = False)

In [61]:
dv.fit(dicts)

DictVectorizer(sparse=False)

In [64]:
dv.get_feature_names_out()

array(['contract=month-to-month', 'contract=one_year',
       'contract=two_year', 'gender=female', 'gender=male'], dtype=object)

In [62]:
dv.transform(dicts)

array([[0., 0., 1., 1., 0.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0.],
       [1., 0., 0., 1., 0.],
       [0., 0., 1., 1., 0.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0.],
       [0., 0., 1., 1., 0.],
       [1., 0., 0., 1., 0.],
       [0., 0., 1., 1., 0.],
       [1., 0., 0., 0., 1.],
       [0., 0., 1., 1., 0.],
       [1., 0., 0., 1., 0.],
       [1., 0., 0., 1., 0.],
       [1., 0., 0., 0., 1.],
       [0., 0., 1., 1., 0.],
       [1., 0., 0., 1., 0.],
       [0., 1., 0., 0., 1.],
       [0., 0., 1., 0., 1.],
       [1., 0., 0., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 0., 1., 0.],
       [0., 0., 1., 1., 0.],
       [1., 0., 0., 0., 1.],
       [0., 0., 1., 0., 1.],
       [1., 0., 0., 1., 0.],
       [1., 0., 0., 1., 0.],
       [1., 0., 0., 1., 0.],
       [0., 1., 0., 1., 0.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0.],
       [1., 0., 0., 0., 1.],
       [0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0.],
       [0., 0., 1., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0.],
       [1., 0., 0., 1., 0.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 0., 0., 1.],
       [0., 0., 1., 1., 0.],
       [1., 0., 0., 0., 1.],
       [0., 0., 1., 1., 0.],
       [0., 0., 1., 0., 1.],
       [1., 0., 0., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 0., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 0., 1., 0.],
       [1., 0., 0., 0., 1.],
       [0., 1., 0., 0., 1.],
       [0., 0., 1., 1., 0.],
       [0., 0., 1., 1., 0.],
       [0., 0., 1., 0., 1.],
       [0., 0., 1., 1., 0.],
       [1., 0., 0., 0., 1.],
       [0., 0., 1., 1., 0.],
       [1., 0., 0., 0., 1.],
       [0., 1., 0., 0., 1.],
       [0., 1., 0., 0., 1.],
       [0., 0., 1., 0., 1.],
       [0., 1., 0., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0.],
       [0., 0., 1., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0.],
       [0., 0., 1., 1., 0.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [0., 1., 0., 1., 0.],
       [0., 1., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0.],
       [1., 0., 0., 0., 1.],
       [0., 1., 0., 1., 0.],
       [0., 0., 1., 0., 1.],
       [0., 1., 0., 0., 1.],
       [1., 0., 0., 1., 0.],
       [0., 1., 0., 0., 1.],
       [1., 0., 0., 1., 0.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0.],
       [0., 1., 0., 0., 1.],
       [1., 0., 0., 1., 0.],
       [1., 0., 0., 0., 1.],
       [0., 1., 0., 0., 1.],
       [1., 0., 0., 0., 1.]])

In [65]:
# Now if we want to add a new feature into this, that too a numerical, the DictVectorize fucntion is smart enough to identify that

In [66]:
df_train[['gender', 'contract', 'tenure']].iloc[:100]
dicts = df_train[['gender', 'contract', 'tenure']].iloc[:100].to_dict(orient = 'records')
dv = DictVectorizer(sparse = False)
dv.fit(dicts)
dv.transform(dicts)

array([[ 0.,  0.,  1.,  1.,  0., 72.],
       [ 1.,  0.,  0.,  0.,  1., 10.],
       [ 1.,  0.,  0.,  1.,  0.,  5.],
       [ 1.,  0.,  0.,  1.,  0.,  5.],
       [ 0.,  0.,  1.,  1.,  0., 18.],
       [ 1.,  0.,  0.,  0.,  1.,  4.],
       [ 1.,  0.,  0.,  0.,  1.,  1.],
       [ 1.,  0.,  0.,  1.,  0.,  1.],
       [ 0.,  0.,  1.,  1.,  0., 72.],
       [ 1.,  0.,  0.,  1.,  0.,  6.],
       [ 0.,  0.,  1.,  1.,  0., 72.],
       [ 1.,  0.,  0.,  0.,  1., 17.],
       [ 0.,  0.,  1.,  1.,  0., 66.],
       [ 1.,  0.,  0.,  1.,  0.,  2.],
       [ 1.,  0.,  0.,  1.,  0.,  4.],
       [ 1.,  0.,  0.,  0.,  1.,  3.],
       [ 0.,  0.,  1.,  1.,  0., 71.],
       [ 1.,  0.,  0.,  1.,  0., 32.],
       [ 0.,  1.,  0.,  0.,  1., 53.],
       [ 0.,  0.,  1.,  0.,  1., 56.],
       [ 1.,  0.,  0.,  0.,  1., 61.],
       [ 0.,  1.,  0.,  1.,  0., 41.],
       [ 1.,  0.,  0.,  1.,  0.,  1.],
       [ 0.,  0.,  1.,  1.,  0.,  3.],
       [ 1.,  0.,  0.,  0.,  1.,  3.],
       [ 0.,  0.,  1.,  0.,  1., 12.],
       [ 1.,  0.,  0.,  1.,  0., 41.],
       [ 1.,  0.,  0.,  1.,  0., 47.],
       [ 1.,  0.,  0.,  1.,  0.,  2.],
       [ 0.,  1.,  0.,  1.,  0., 66.],
       [ 1.,  0.,  0.,  0.,  1.,  8.],
       [ 1.,  0.,  0.,  0.,  1.,  1.],
       [ 0.,  1.,  0.,  1.,  0., 35.],
       [ 0.,  1.,  0.,  1.,  0., 67.],
       [ 1.,  0.,  0.,  0.,  1.,  1.],
       [ 0.,  1.,  0.,  1.,  0., 46.],
       [ 0.,  1.,  0.,  1.,  0., 37.],
       [ 0.,  0.,  1.,  0.,  1., 72.],
       [ 1.,  0.,  0.,  0.,  1., 35.],
       [ 1.,  0.,  0.,  1.,  0., 43.],
       [ 1.,  0.,  0.,  1.,  0., 20.],
       [ 1.,  0.,  0.,  0.,  1., 64.],
       [ 1.,  0.,  0.,  1.,  0.,  6.],
       [ 1.,  0.,  0.,  0.,  1.,  9.],
       [ 1.,  0.,  0.,  0.,  1., 18.],
       [ 0.,  1.,  0.,  1.,  0., 46.],
       [ 1.,  0.,  0.,  0.,  1.,  9.],
       [ 0.,  0.,  1.,  1.,  0., 69.],
       [ 1.,  0.,  0.,  0.,  1., 32.],
       [ 0.,  0.,  1.,  1.,  0., 67.],
       [ 0.,  0.,  1.,  0.,  1., 69.],
       [ 1.,  0.,  0.,  0.,  1.,  6.],
       [ 0.,  1.,  0.,  1.,  0., 30.],
       [ 1.,  0.,  0.,  0.,  1., 30.],
       [ 0.,  1.,  0.,  1.,  0., 58.],
       [ 1.,  0.,  0.,  1.,  0., 18.],
       [ 1.,  0.,  0.,  0.,  1., 34.],
       [ 0.,  1.,  0.,  0.,  1.,  2.],
       [ 0.,  0.,  1.,  1.,  0., 10.],
       [ 0.,  0.,  1.,  1.,  0., 71.],
       [ 0.,  0.,  1.,  0.,  1., 72.],
       [ 0.,  0.,  1.,  1.,  0., 46.],
       [ 1.,  0.,  0.,  0.,  1., 49.],
       [ 0.,  0.,  1.,  1.,  0., 65.],
       [ 1.,  0.,  0.,  0.,  1., 15.],
       [ 0.,  1.,  0.,  0.,  1., 58.],
       [ 0.,  1.,  0.,  0.,  1., 66.],
       [ 0.,  0.,  1.,  0.,  1., 66.],
       [ 0.,  1.,  0.,  0.,  1., 68.],
       [ 0.,  1.,  0.,  1.,  0., 45.],
       [ 1.,  0.,  0.,  0.,  1.,  1.],
       [ 1.,  0.,  0.,  0.,  1., 11.],
       [ 1.,  0.,  0.,  1.,  0., 18.],
       [ 0.,  0.,  1.,  0.,  1., 71.],
       [ 1.,  0.,  0.,  0.,  1.,  4.],
       [ 1.,  0.,  0.,  1.,  0., 13.],
       [ 0.,  0.,  1.,  1.,  0., 50.],
       [ 1.,  0.,  0.,  0.,  1., 12.],
       [ 1.,  0.,  0.,  0.,  1.,  1.],
       [ 0.,  1.,  0.,  1.,  0.,  7.],
       [ 0.,  1.,  0.,  0.,  1., 71.],
       [ 1.,  0.,  0.,  0.,  1.,  1.],
       [ 1.,  0.,  0.,  0.,  1., 21.],
       [ 1.,  0.,  0.,  1.,  0., 12.],
       [ 1.,  0.,  0.,  0.,  1.,  1.],
       [ 1.,  0.,  0.,  1.,  0., 33.],
       [ 1.,  0.,  0.,  0.,  1., 46.],
       [ 0.,  1.,  0.,  1.,  0., 44.],
       [ 0.,  0.,  1.,  0.,  1., 70.],
       [ 0.,  1.,  0.,  0.,  1.,  7.],
       [ 1.,  0.,  0.,  1.,  0., 18.],
       [ 0.,  1.,  0.,  0.,  1., 54.],
       [ 1.,  0.,  0.,  1.,  0., 35.],
       [ 1.,  0.,  0.,  0.,  1.,  5.],
       [ 1.,  0.,  0.,  1.,  0., 35.],
       [ 0.,  1.,  0.,  0.,  1., 39.],
       [ 1.,  0.,  0.,  1.,  0., 19.],
       [ 1.,  0.,  0.,  0.,  1., 21.],
       [ 0.,  1.,  0.,  0.,  1., 43.],
       [ 1.,  0.,  0.,  0.,  1., 19.]])

In [68]:
# Now lets use the full training dataset
train_dicts = df_train[categorical + numerical].to_dict(orient = 'records')

In [69]:
dv = DictVectorizer(sparse = False)

In [73]:
dv.fit(train_dicts)
X_train = dv.transform(train_dicts)

# Instead we can use dv.fit_transform() function to do both steps in on go

In [74]:
val_dicts = df_val[categorical + numerical].to_dict(orient = 'records')

In [75]:
X_val = dv.transform(val_dicts)